USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA GOLD;

SELECT
    'FACT_SALES' AS TABLE_NAME,
    'ORDER_ID' AS COLUMN_NAME,
    COUNT(*) AS NULL_COUNT
FROM FACT_SALES
WHERE ORDER_ID IS NULL

UNION ALL

SELECT
    'FACT_SALES' AS TABLE_NAME,
    'CUSTOMER_ID' AS COLUMN_NAME,
    COUNT(*) AS NULL_COUNT
FROM FACT_SALES
WHERE CUSTOMER_ID IS NULL

UNION ALL

SELECT
    'FACT_SALES' AS TABLE_NAME,
    'CUSTOMER_UNIQUE_ID' AS COLUMN_NAME,
    COUNT(*) AS NULL_COUNT
FROM FACT_SALES
WHERE CUSTOMER_UNIQUE_ID IS NULL

UNION ALL

SELECT
    'FACT_SALES' AS TABLE_NAME,
    'PRODUCT_ID' AS COLUMN_NAME,
    COUNT(*) AS NULL_COUNT
FROM FACT_SALES
WHERE PRODUCT_ID IS NULL

UNION ALL

SELECT
    'FACT_SALES' AS TABLE_NAME,
    'ORDER_PURCHASE_TIMESTAMP' AS COLUMN_NAME,
    COUNT(*) AS NULL_COUNT
FROM FACT_SALES
WHERE ORDER_PURCHASE_TIMESTAMP IS NULL

UNION ALL

SELECT
    'FACT_SALES' AS TABLE_NAME,
    'TOTAL_SALE_AMOUNT' AS COLUMN_NAME,
    COUNT(*) AS NULL_COUNT
FROM FACT_SALES
WHERE TOTAL_SALE_AMOUNT IS NULL;