USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA GOLD;

SELECT
    'Null Check - Order ID' AS CHECK_NAME,
    CASE WHEN COUNT_IF(ORDER_ID IS NULL) = 0 THEN 'PASS' ELSE 'FAIL' END AS STATUS,
    COUNT_IF(ORDER_ID IS NULL) AS FAILED_RECORDS
FROM FACT_SALES

UNION ALL

SELECT
    'Null Check - Customer ID',
    CASE WHEN COUNT_IF(CUSTOMER_ID IS NULL) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT_IF(CUSTOMER_ID IS NULL)
FROM FACT_SALES

UNION ALL

SELECT
    'Null Check - Product ID',
    CASE WHEN COUNT_IF(PRODUCT_ID IS NULL) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT_IF(PRODUCT_ID IS NULL)
FROM FACT_SALES

UNION ALL

SELECT
    'Null Check - Order Date',
    CASE WHEN COUNT_IF(ORDER_DATE IS NULL) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT_IF(ORDER_DATE IS NULL)
FROM FACT_SALES

UNION ALL

SELECT
    'Null Check - Total Sale Amount',
    CASE WHEN COUNT_IF(TOTAL_SALE_AMOUNT IS NULL) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT_IF(TOTAL_SALE_AMOUNT IS NULL)
FROM FACT_SALES

UNION ALL

SELECT
    'Negative Total Sale Amount Check',
    CASE WHEN COUNT_IF(TOTAL_SALE_AMOUNT < 0) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT_IF(TOTAL_SALE_AMOUNT < 0)
FROM FACT_SALES;