USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA GOLD;

SELECT
    'FACT_SALES - Null SALES_SK' AS CHECK_NAME,
    CASE WHEN COUNT_IF(SALES_SK IS NULL) = 0 THEN 'PASS' ELSE 'FAIL' END AS STATUS,
    COUNT_IF(SALES_SK IS NULL) AS FAILED_RECORDS
FROM FACT_SALES

UNION ALL

SELECT
    'FACT_SALES - Null CUSTOMER_SK',
    CASE WHEN COUNT_IF(CUSTOMER_SK IS NULL) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT_IF(CUSTOMER_SK IS NULL)
FROM FACT_SALES

UNION ALL

SELECT
    'FACT_SALES - Null PRODUCT_SK',
    CASE WHEN COUNT_IF(PRODUCT_SK IS NULL) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT_IF(PRODUCT_SK IS NULL)
FROM FACT_SALES

UNION ALL

SELECT
    'FACT_SALES - Null DATE_SK',
    CASE WHEN COUNT_IF(DATE_SK IS NULL) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT_IF(DATE_SK IS NULL)
FROM FACT_SALES

UNION ALL

SELECT
    'FACT_SALES - Null ORDER_ID',
    CASE WHEN COUNT_IF(ORDER_ID IS NULL) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT_IF(ORDER_ID IS NULL)
FROM FACT_SALES

UNION ALL

SELECT
    'FACT_SALES - Null CUSTOMER_UNIQUE_ID',
    CASE WHEN COUNT_IF(CUSTOMER_UNIQUE_ID IS NULL) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT_IF(CUSTOMER_UNIQUE_ID IS NULL)
FROM FACT_SALES

UNION ALL

SELECT
    'FACT_SALES - Null TOTAL_SALE_AMOUNT',
    CASE WHEN COUNT_IF(TOTAL_SALE_AMOUNT IS NULL) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT_IF(TOTAL_SALE_AMOUNT IS NULL)
FROM FACT_SALES

UNION ALL

SELECT
    'FACT_SALES - Negative TOTAL_SALE_AMOUNT',
    CASE WHEN COUNT_IF(TOTAL_SALE_AMOUNT < 0) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT_IF(TOTAL_SALE_AMOUNT < 0)
FROM FACT_SALES

UNION ALL

SELECT
    'FACT_SALES - Null LOAD_TIMESTAMP',
    CASE WHEN COUNT_IF(LOAD_TIMESTAMP IS NULL) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT_IF(LOAD_TIMESTAMP IS NULL)
FROM FACT_SALES

UNION ALL

SELECT
    'DIM_CUSTOMER - Null CUSTOMER_SK',
    CASE WHEN COUNT_IF(CUSTOMER_SK IS NULL) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT_IF(CUSTOMER_SK IS NULL)
FROM DIM_CUSTOMER

UNION ALL

SELECT
    'DIM_CUSTOMER - Null CUSTOMER_UNIQUE_ID',
    CASE WHEN COUNT_IF(CUSTOMER_UNIQUE_ID IS NULL) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT_IF(CUSTOMER_UNIQUE_ID IS NULL)
FROM DIM_CUSTOMER

UNION ALL

SELECT
    'DIM_CUSTOMER - Duplicate CUSTOMER_UNIQUE_ID',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT(*)
FROM (
    SELECT CUSTOMER_UNIQUE_ID
    FROM DIM_CUSTOMER
    GROUP BY CUSTOMER_UNIQUE_ID
    HAVING COUNT(*) > 1
)

UNION ALL

SELECT
    'DIM_CUSTOMER - Null LOAD_TIMESTAMP',
    CASE WHEN COUNT_IF(LOAD_TIMESTAMP IS NULL) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT_IF(LOAD_TIMESTAMP IS NULL)
FROM DIM_CUSTOMER

UNION ALL

SELECT
    'DIM_PRODUCT - Null PRODUCT_SK',
    CASE WHEN COUNT_IF(PRODUCT_SK IS NULL) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT_IF(PRODUCT_SK IS NULL)
FROM DIM_PRODUCT

UNION ALL

SELECT
    'DIM_PRODUCT - Null PRODUCT_ID',
    CASE WHEN COUNT_IF(PRODUCT_ID IS NULL) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT_IF(PRODUCT_ID IS NULL)
FROM DIM_PRODUCT

UNION ALL

SELECT
    'DIM_PRODUCT - Null PRODUCT_CATEGORY_NAME',
    CASE WHEN COUNT_IF(PRODUCT_CATEGORY_NAME IS NULL) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT_IF(PRODUCT_CATEGORY_NAME IS NULL)
FROM DIM_PRODUCT

UNION ALL

SELECT
    'DIM_PRODUCT - Duplicate PRODUCT_ID',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT(*)
FROM (
    SELECT PRODUCT_ID
    FROM DIM_PRODUCT
    GROUP BY PRODUCT_ID
    HAVING COUNT(*) > 1
)

UNION ALL

SELECT
    'DIM_PRODUCT - Null LOAD_TIMESTAMP',
    CASE WHEN COUNT_IF(LOAD_TIMESTAMP IS NULL) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT_IF(LOAD_TIMESTAMP IS NULL)
FROM DIM_PRODUCT

UNION ALL

SELECT
    'DIM_DATE - Null DATE_SK',
    CASE WHEN COUNT_IF(DATE_SK IS NULL) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT_IF(DATE_SK IS NULL)
FROM DIM_DATE

UNION ALL

SELECT
    'DIM_DATE - Null ORDER_DATE',
    CASE WHEN COUNT_IF(ORDER_DATE IS NULL) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT_IF(ORDER_DATE IS NULL)
FROM DIM_DATE

UNION ALL

SELECT
    'DIM_DATE - Duplicate DATE_SK',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT(*)
FROM (
    SELECT DATE_SK
    FROM DIM_DATE
    GROUP BY DATE_SK
    HAVING COUNT(*) > 1
)

UNION ALL

SELECT
    'DIM_DATE - Null LOAD_TIMESTAMP',
    CASE WHEN COUNT_IF(LOAD_TIMESTAMP IS NULL) = 0 THEN 'PASS' ELSE 'FAIL' END,
    COUNT_IF(LOAD_TIMESTAMP IS NULL)
FROM DIM_DATE;