USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA GOLD;

SELECT
    'Null Check - Order ID' AS CHECK_NAME,
    CASE
        WHEN COUNT_IF(ORDER_ID IS NULL) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END AS STATUS,
    COUNT_IF(ORDER_ID IS NULL) AS FAILED_RECORDS
FROM FACT_SALES

UNION ALL

SELECT
    'Null Check - Customer ID',
    CASE
        WHEN COUNT_IF(CUSTOMER_ID IS NULL) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END,
    COUNT_IF(CUSTOMER_ID IS NULL)
FROM FACT_SALES

UNION ALL

SELECT
    'Null Check - Product ID',
    CASE
        WHEN COUNT_IF(PRODUCT_ID IS NULL) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END,
    COUNT_IF(PRODUCT_ID IS NULL)
FROM FACT_SALES

UNION ALL

SELECT
    'Null Check - Price',
    CASE
        WHEN COUNT_IF(PRICE IS NULL) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END,
    COUNT_IF(PRICE IS NULL)
FROM FACT_SALES

UNION ALL

SELECT
    'Negative Price Check',
    CASE
        WHEN COUNT_IF(PRICE < 0) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END,
    COUNT_IF(PRICE < 0)
FROM FACT_SALES

UNION ALL

SELECT
    'Negative Freight Check',
    CASE
        WHEN COUNT_IF(FREIGHT_VALUE < 0) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END,
    COUNT_IF(FREIGHT_VALUE < 0)
FROM FACT_SALES;