USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA GOLD;

SELECT
    ORDER_ID,
    ORDER_ITEM_ID,
    PRODUCT_ID,
    CUSTOMER_ID,
    COUNT(*) AS DUPLICATE_COUNT
FROM FACT_SALES
GROUP BY
    ORDER_ID,
    ORDER_ITEM_ID,
    PRODUCT_ID,
    CUSTOMER_ID
HAVING COUNT(*) > 1
ORDER BY DUPLICATE_COUNT DESC;