USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA GOLD;

SELECT
    'FACT_SALES' AS TABLE_NAME,
    MIN(ORDER_PURCHASE_TIMESTAMP) AS EARLIEST_ORDER_TIMESTAMP,
    MAX(ORDER_PURCHASE_TIMESTAMP) AS LATEST_ORDER_TIMESTAMP,
    DATEDIFF('DAY', MAX(ORDER_PURCHASE_TIMESTAMP), CURRENT_TIMESTAMP()) AS DAYS_SINCE_LATEST_ORDER
FROM FACT_SALES;