USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA GOLD;

SELECT
    'FACT_SALES' AS TABLE_NAME,
    MIN(ORDER_DATE) AS EARLIEST_ORDER_DATE,
    MAX(ORDER_DATE) AS LATEST_ORDER_DATE,
    DATEDIFF('DAY', MAX(ORDER_DATE), CURRENT_DATE()) AS DAYS_SINCE_LATEST_ORDER
FROM FACT_SALES;