USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA GOLD;

SELECT
    'FACT_SALES' AS TABLE_NAME,
    COUNT(*) AS TOTAL_ROWS,
    SUM(CASE WHEN SALES_SK IS NULL THEN 1 ELSE 0 END) AS NULL_SALES_SK,
    SUM(CASE WHEN CUSTOMER_SK IS NULL THEN 1 ELSE 0 END) AS NULL_CUSTOMER_SK,
    SUM(CASE WHEN PRODUCT_SK IS NULL THEN 1 ELSE 0 END) AS NULL_PRODUCT_SK,
    SUM(CASE WHEN DATE_SK IS NULL THEN 1 ELSE 0 END) AS NULL_DATE_SK,
    SUM(CASE WHEN ORDER_ID IS NULL THEN 1 ELSE 0 END) AS NULL_ORDER_ID,
    SUM(CASE WHEN ORDER_ITEM_ID IS NULL THEN 1 ELSE 0 END) AS NULL_ORDER_ITEM_ID,
    SUM(CASE WHEN CUSTOMER_ID IS NULL THEN 1 ELSE 0 END) AS NULL_CUSTOMER_ID,
    SUM(CASE WHEN PRODUCT_ID IS NULL THEN 1 ELSE 0 END) AS NULL_PRODUCT_ID,
    SUM(CASE WHEN ORDER_DATE IS NULL THEN 1 ELSE 0 END) AS NULL_ORDER_DATE,
    SUM(CASE WHEN PRICE IS NULL THEN 1 ELSE 0 END) AS NULL_PRICE,
    SUM(CASE WHEN FREIGHT_VALUE IS NULL THEN 1 ELSE 0 END) AS NULL_FREIGHT_VALUE,
    SUM(CASE WHEN TOTAL_SALE_AMOUNT IS NULL THEN 1 ELSE 0 END) AS NULL_TOTAL_SALE_AMOUNT,
    SUM(CASE WHEN LOAD_TIMESTAMP IS NULL THEN 1 ELSE 0 END) AS NULL_LOAD_TIMESTAMP
FROM FACT_SALES;