USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA GOLD;

SELECT
    'FACT_SALES' AS TABLE_NAME,
    COUNT(*) AS TOTAL_ROWS,
    SUM(CASE WHEN ORDER_ID IS NULL THEN 1 ELSE 0 END) AS NULL_ORDER_ID,
    SUM(CASE WHEN CUSTOMER_ID IS NULL THEN 1 ELSE 0 END) AS NULL_CUSTOMER_ID,
    SUM(CASE WHEN PRODUCT_ID IS NULL THEN 1 ELSE 0 END) AS NULL_PRODUCT_ID,
    SUM(CASE WHEN PRICE IS NULL THEN 1 ELSE 0 END) AS NULL_PRICE,
    SUM(CASE WHEN FREIGHT_VALUE IS NULL THEN 1 ELSE 0 END) AS NULL_FREIGHT_VALUE
FROM FACT_SALES;