USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA GOLD;

SELECT
    'FACT_SALES missing customer dimension surrogate key match' AS CHECK_NAME,
    COUNT(*) AS FAILED_RECORDS
FROM FACT_SALES fs
LEFT JOIN DIM_CUSTOMER dc
    ON fs.CUSTOMER_SK = dc.CUSTOMER_SK
WHERE dc.CUSTOMER_SK IS NULL

UNION ALL

SELECT
    'FACT_SALES missing product dimension surrogate key match',
    COUNT(*) AS FAILED_RECORDS
FROM FACT_SALES fs
LEFT JOIN DIM_PRODUCT dp
    ON fs.PRODUCT_SK = dp.PRODUCT_SK
WHERE dp.PRODUCT_SK IS NULL

UNION ALL

SELECT
    'FACT_SALES missing date dimension surrogate key match',
    COUNT(*) AS FAILED_RECORDS
FROM FACT_SALES fs
LEFT JOIN DIM_DATE dd
    ON fs.DATE_SK = dd.DATE_SK
WHERE dd.DATE_SK IS NULL;