USE DATABASE RETAIL_ANALYTICS_DB;

SELECT
    'CUSTOMERS' AS DATASET,
    (SELECT COUNT(*) FROM BRONZE.BRONZE_CUSTOMERS) AS BRONZE_COUNT,
    (SELECT COUNT(*) FROM SILVER.SILVER_CUSTOMERS) AS SILVER_COUNT,
    (SELECT COUNT(*) FROM GOLD.DIM_CUSTOMER) AS GOLD_COUNT

UNION ALL

SELECT
    'ORDERS',
    (SELECT COUNT(*) FROM BRONZE.BRONZE_ORDERS),
    (SELECT COUNT(*) FROM SILVER.SILVER_ORDERS),
    NULL

UNION ALL

SELECT
    'PRODUCTS',
    (SELECT COUNT(*) FROM BRONZE.BRONZE_PRODUCTS),
    (SELECT COUNT(*) FROM SILVER.SILVER_PRODUCTS),
    (SELECT COUNT(*) FROM GOLD.DIM_PRODUCT)

UNION ALL

SELECT
    'ORDER_ITEMS',
    (SELECT COUNT(*) FROM BRONZE.BRONZE_ORDER_ITEMS),
    (SELECT COUNT(*) FROM SILVER.SILVER_ORDER_ITEMS),
    (SELECT COUNT(*) FROM GOLD.FACT_SALES);