USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA SILVER;

CREATE OR REPLACE TABLE SILVER_CUSTOMERS
(
    CUSTOMER_ID STRING,
    CUSTOMER_UNIQUE_ID STRING,
    CUSTOMER_CITY STRING,
    CUSTOMER_STATE STRING,
    LOAD_TIMESTAMP TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE SILVER_ORDERS
(
    ORDER_ID STRING,
    CUSTOMER_ID STRING,
    ORDER_STATUS STRING,
    ORDER_PURCHASE_TIMESTAMP TIMESTAMP,
    ORDER_DELIVERED_CUSTOMER_DATE TIMESTAMP,
    LOAD_TIMESTAMP TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE SILVER_PRODUCTS
(
    PRODUCT_ID STRING,
    PRODUCT_CATEGORY_NAME STRING,
    PRODUCT_WEIGHT_G NUMBER,
    LOAD_TIMESTAMP TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE SILVER_ORDER_ITEMS
(
    ORDER_ID STRING,
    ORDER_ITEM_ID NUMBER,
    PRODUCT_ID STRING,
    PRICE NUMBER(10,2),
    FREIGHT_VALUE NUMBER(10,2),
    LOAD_TIMESTAMP TIMESTAMP_NTZ
);