USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA SILVER;

INSERT INTO SILVER_CUSTOMERS
SELECT
    CUSTOMER_ID,
    CUSTOMER_UNIQUE_ID,
    CUSTOMER_CITY,
    CUSTOMER_STATE
FROM (
    SELECT
        CUSTOMER_ID,
        CUSTOMER_UNIQUE_ID,
        UPPER(TRIM(CUSTOMER_CITY)) AS CUSTOMER_CITY,
        UPPER(TRIM(CUSTOMER_STATE)) AS CUSTOMER_STATE,
        ROW_NUMBER() OVER (
            PARTITION BY CUSTOMER_ID
            ORDER BY CUSTOMER_UNIQUE_ID
        ) AS ROW_NUM
    FROM BRONZE.BRONZE_CUSTOMERS
    WHERE CUSTOMER_ID IS NOT NULL
)
WHERE ROW_NUM = 1;

INSERT INTO SILVER_ORDERS
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_STATUS,
    ORDER_PURCHASE_TIMESTAMP,
    ORDER_DELIVERED_CUSTOMER_DATE
FROM (
    SELECT
        ORDER_ID,
        CUSTOMER_ID,
        ORDER_STATUS,
        ORDER_PURCHASE_TIMESTAMP,
        ORDER_DELIVERED_CUSTOMER_DATE,
        ROW_NUMBER() OVER (
            PARTITION BY ORDER_ID
            ORDER BY ORDER_PURCHASE_TIMESTAMP DESC
        ) AS ROW_NUM
    FROM BRONZE.BRONZE_ORDERS
    WHERE ORDER_ID IS NOT NULL
      AND CUSTOMER_ID IS NOT NULL
      AND ORDER_PURCHASE_TIMESTAMP IS NOT NULL
)
WHERE ROW_NUM = 1;

INSERT INTO SILVER_PRODUCTS
SELECT
    PRODUCT_ID,
    PRODUCT_CATEGORY_NAME,
    PRODUCT_WEIGHT_G
FROM (
    SELECT
        PRODUCT_ID,
        COALESCE(PRODUCT_CATEGORY_NAME, 'UNKNOWN') AS PRODUCT_CATEGORY_NAME,
        PRODUCT_WEIGHT_G,
        ROW_NUMBER() OVER (
            PARTITION BY PRODUCT_ID
            ORDER BY PRODUCT_WEIGHT_G DESC NULLS LAST
        ) AS ROW_NUM
    FROM BRONZE.BRONZE_PRODUCTS
    WHERE PRODUCT_ID IS NOT NULL
)
WHERE ROW_NUM = 1;

INSERT INTO SILVER_ORDER_ITEMS
SELECT
    ORDER_ID,
    ORDER_ITEM_ID,
    PRODUCT_ID,
    PRICE,
    FREIGHT_VALUE
FROM (
    SELECT
        ORDER_ID,
        ORDER_ITEM_ID,
        PRODUCT_ID,
        PRICE,
        FREIGHT_VALUE,
        ROW_NUMBER() OVER (
            PARTITION BY ORDER_ID, ORDER_ITEM_ID
            ORDER BY PRODUCT_ID
        ) AS ROW_NUM
    FROM BRONZE.BRONZE_ORDER_ITEMS
    WHERE ORDER_ID IS NOT NULL
      AND ORDER_ITEM_ID IS NOT NULL
      AND PRODUCT_ID IS NOT NULL
      AND PRICE IS NOT NULL
)
WHERE ROW_NUM = 1;