INSERT INTO SILVER.SILVER_CUSTOMERS
SELECT DISTINCT
       CUSTOMER_ID,
       CUSTOMER_UNIQUE_ID,
       UPPER(TRIM(CUSTOMER_CITY)),
       UPPER(TRIM(CUSTOMER_STATE))
FROM BRONZE.BRONZE_CUSTOMERS
WHERE CUSTOMER_ID IS NOT NULL;

INSERT INTO SILVER.SILVER_ORDERS
SELECT DISTINCT
       ORDER_ID,
       CUSTOMER_ID,
       ORDER_STATUS,
       ORDER_PURCHASE_TIMESTAMP,
       ORDER_DELIVERED_CUSTOMER_DATE
FROM BRONZE.BRONZE_ORDERS
WHERE ORDER_ID IS NOT NULL;

INSERT INTO SILVER.SILVER_PRODUCTS
SELECT DISTINCT
       PRODUCT_ID,
       PRODUCT_CATEGORY_NAME,
       PRODUCT_WEIGHT_G
FROM BRONZE.BRONZE_PRODUCTS
WHERE PRODUCT_ID IS NOT NULL;

INSERT INTO SILVER.SILVER_ORDER_ITEMS
SELECT DISTINCT
       ORDER_ID,
       ORDER_ITEM_ID,
       PRODUCT_ID,
       PRICE,
       FREIGHT_VALUE
FROM BRONZE.BRONZE_ORDER_ITEMS
WHERE ORDER_ID IS NOT NULL;
