SELECT COUNT(*) FROM SILVER_CUSTOMERS;

SELECT COUNT(*) FROM SILVER_ORDERS;

SELECT COUNT(*) FROM SILVER_PRODUCTS;

SELECT COUNT(*) FROM SILVER_ORDER_ITEMS;

SELECT CUSTOMER_ID,
       COUNT(*)
FROM SILVER_CUSTOMERS
GROUP BY CUSTOMER_ID
HAVING COUNT(*) > 1;

SELECT ORDER_ID,
       COUNT(*)
FROM SILVER_ORDERS
GROUP BY ORDER_ID
HAVING COUNT(*) > 1;
