USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA SILVER;

SELECT 'SILVER_CUSTOMERS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM SILVER_CUSTOMERS

UNION ALL

SELECT 'SILVER_ORDERS', COUNT(*)
FROM SILVER_ORDERS

UNION ALL

SELECT 'SILVER_PRODUCTS', COUNT(*)
FROM SILVER_PRODUCTS

UNION ALL

SELECT 'SILVER_ORDER_ITEMS', COUNT(*)
FROM SILVER_ORDER_ITEMS;

SELECT
    CUSTOMER_ID,
    COUNT(*) AS DUPLICATE_COUNT
FROM SILVER_CUSTOMERS
GROUP BY CUSTOMER_ID
HAVING COUNT(*) > 1;

SELECT
    ORDER_ID,
    COUNT(*) AS DUPLICATE_COUNT
FROM SILVER_ORDERS
GROUP BY ORDER_ID
HAVING COUNT(*) > 1;

SELECT
    ORDER_ID,
    ORDER_ITEM_ID,
    PRODUCT_ID,
    COUNT(*) AS DUPLICATE_COUNT
FROM SILVER_ORDER_ITEMS
GROUP BY
    ORDER_ID,
    ORDER_ITEM_ID,
    PRODUCT_ID
HAVING COUNT(*) > 1;