USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA GOLD;

SELECT
    ROUND(SUM(TOTAL_SALE_AMOUNT), 2) AS TOTAL_REVENUE,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    COUNT(DISTINCT CUSTOMER_ID) AS TOTAL_CUSTOMERS,
    COUNT(DISTINCT PRODUCT_ID) AS TOTAL_PRODUCTS,
    ROUND(AVG(TOTAL_SALE_AMOUNT), 2) AS AVG_ORDER_ITEM_VALUE
FROM FACT_SALES;