USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA GOLD;

WITH order_totals AS (
    SELECT
        ORDER_ID,
        SUM(TOTAL_SALE_AMOUNT) AS ORDER_TOTAL
    FROM FACT_SALES
    GROUP BY ORDER_ID
),

fact_summary AS (
    SELECT
        ROUND(SUM(TOTAL_SALE_AMOUNT), 2) AS TOTAL_REVENUE,
        COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
        COUNT(DISTINCT CUSTOMER_UNIQUE_ID) AS TOTAL_CUSTOMERS,
        COUNT(DISTINCT PRODUCT_ID) AS TOTAL_PRODUCTS,
        ROUND(AVG(TOTAL_SALE_AMOUNT), 2) AS AVG_LINE_ITEM_VALUE
    FROM FACT_SALES
)

SELECT
    fs.TOTAL_REVENUE,
    fs.TOTAL_ORDERS,
    fs.TOTAL_CUSTOMERS,
    fs.TOTAL_PRODUCTS,
    fs.AVG_LINE_ITEM_VALUE,
    ROUND(AVG(ot.ORDER_TOTAL), 2) AS AVG_ORDER_VALUE
FROM fact_summary fs
CROSS JOIN order_totals ot
GROUP BY
    fs.TOTAL_REVENUE,
    fs.TOTAL_ORDERS,
    fs.TOTAL_CUSTOMERS,
    fs.TOTAL_PRODUCTS,
    fs.AVG_LINE_ITEM_VALUE;