USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA GOLD;

SELECT
    'FACT_SALES_ROW_COUNT' AS CHECK_NAME,
    COUNT(*) AS CHECK_VALUE,
    CURRENT_TIMESTAMP() AS CHECK_TIMESTAMP
FROM FACT_SALES

UNION ALL

SELECT
    'DISTINCT_ORDER_COUNT',
    COUNT(DISTINCT ORDER_ID),
    CURRENT_TIMESTAMP()
FROM FACT_SALES

UNION ALL

SELECT
    'DISTINCT_CUSTOMER_COUNT',
    COUNT(DISTINCT CUSTOMER_UNIQUE_ID),
    CURRENT_TIMESTAMP()
FROM FACT_SALES

UNION ALL

SELECT
    'NULL_CUSTOMER_UNIQUE_ID_COUNT',
    COUNT(*),
    CURRENT_TIMESTAMP()
FROM FACT_SALES
WHERE CUSTOMER_UNIQUE_ID IS NULL

UNION ALL

SELECT
    'TOTAL_REVENUE',
    ROUND(SUM(TOTAL_SALE_AMOUNT), 2),
    CURRENT_TIMESTAMP()
FROM FACT_SALES

UNION ALL

SELECT
    'NEGATIVE_REVENUE_ROW_COUNT',
    COUNT(*),
    CURRENT_TIMESTAMP()
FROM FACT_SALES
WHERE TOTAL_SALE_AMOUNT < 0;