USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA GOLD;

SELECT
    'FACT_SALES' AS TABLE_NAME,
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT ORDER_ID) AS DISTINCT_ORDERS,
    COUNT(DISTINCT CUSTOMER_ID) AS DISTINCT_CUSTOMERS,
    COUNT(DISTINCT PRODUCT_ID) AS DISTINCT_PRODUCTS,
    ROUND(SUM(PRICE + FREIGHT_VALUE), 2) AS TOTAL_REVENUE,
    MIN(ORDER_PURCHASE_TIMESTAMP) AS FIRST_ORDER_DATE,
    MAX(ORDER_PURCHASE_TIMESTAMP) AS LAST_ORDER_DATE
FROM FACT_SALES;