USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA GOLD;

CREATE OR REPLACE TABLE FACT_SALES AS
SELECT
    oi.ORDER_ID,
    oi.ORDER_ITEM_ID,
    oi.PRODUCT_ID,
    o.CUSTOMER_ID,
    o.ORDER_PURCHASE_TIMESTAMP,
    CAST(o.ORDER_PURCHASE_TIMESTAMP AS DATE) AS ORDER_DATE,
    oi.PRICE,
    oi.FREIGHT_VALUE,
    oi.PRICE + oi.FREIGHT_VALUE AS TOTAL_SALE_AMOUNT
FROM SILVER.SILVER_ORDER_ITEMS oi
INNER JOIN SILVER.SILVER_ORDERS o
    ON oi.ORDER_ID = o.ORDER_ID;