USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA GOLD;

CREATE OR REPLACE TABLE DIM_CUSTOMER AS
SELECT
    ROW_NUMBER() OVER (ORDER BY CUSTOMER_ID) AS CUSTOMER_SK,
    CUSTOMER_ID,
    CUSTOMER_UNIQUE_ID,
    CUSTOMER_CITY,
    CUSTOMER_STATE,
    CURRENT_TIMESTAMP() AS LOAD_TIMESTAMP
FROM SILVER.SILVER_CUSTOMERS;

CREATE OR REPLACE TABLE DIM_PRODUCT AS
SELECT
    ROW_NUMBER() OVER (ORDER BY PRODUCT_ID) AS PRODUCT_SK,
    PRODUCT_ID,
    PRODUCT_CATEGORY_NAME,
    PRODUCT_WEIGHT_G,
    CURRENT_TIMESTAMP() AS LOAD_TIMESTAMP
FROM SILVER.SILVER_PRODUCTS;

CREATE OR REPLACE TABLE DIM_DATE AS
SELECT DISTINCT
    TO_NUMBER(TO_CHAR(CAST(ORDER_PURCHASE_TIMESTAMP AS DATE), 'YYYYMMDD')) AS DATE_SK,
    CAST(ORDER_PURCHASE_TIMESTAMP AS DATE) AS ORDER_DATE,
    YEAR(ORDER_PURCHASE_TIMESTAMP) AS ORDER_YEAR,
    MONTH(ORDER_PURCHASE_TIMESTAMP) AS ORDER_MONTH,
    DAY(ORDER_PURCHASE_TIMESTAMP) AS ORDER_DAY,
    DAYOFWEEK(ORDER_PURCHASE_TIMESTAMP) AS DAY_OF_WEEK,
    CURRENT_TIMESTAMP() AS LOAD_TIMESTAMP
FROM SILVER.SILVER_ORDERS
WHERE ORDER_PURCHASE_TIMESTAMP IS NOT NULL;