USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA GOLD;

CREATE OR REPLACE TABLE DIM_CUSTOMERS AS
SELECT
    CUSTOMER_ID,
    CUSTOMER_UNIQUE_ID,
    CUSTOMER_CITY,
    CUSTOMER_STATE
FROM SILVER.SILVER_CUSTOMERS;

CREATE OR REPLACE TABLE DIM_PRODUCTS AS
SELECT
    PRODUCT_ID,
    PRODUCT_CATEGORY_NAME,
    PRODUCT_WEIGHT_G
FROM SILVER.SILVER_PRODUCTS;