USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA GOLD;

CREATE OR REPLACE TABLE FACT_SALES AS
WITH sales_base AS (
    SELECT
        oi.ORDER_ID,
        oi.ORDER_ITEM_ID,
        oi.PRODUCT_ID,
        o.CUSTOMER_ID,
        c.CUSTOMER_UNIQUE_ID,
        o.ORDER_PURCHASE_TIMESTAMP,
        CAST(o.ORDER_PURCHASE_TIMESTAMP AS DATE) AS ORDER_DATE,
        oi.PRICE,
        oi.FREIGHT_VALUE,
        oi.PRICE + oi.FREIGHT_VALUE AS TOTAL_SALE_AMOUNT
    FROM SILVER.SILVER_ORDER_ITEMS oi
    INNER JOIN SILVER.SILVER_ORDERS o
        ON oi.ORDER_ID = o.ORDER_ID
    INNER JOIN SILVER.SILVER_CUSTOMERS c
        ON o.CUSTOMER_ID = c.CUSTOMER_ID
)

SELECT
    ROW_NUMBER() OVER (
        ORDER BY sb.ORDER_ID, sb.ORDER_ITEM_ID
    ) AS SALES_SK,
    dc.CUSTOMER_SK,
    dp.PRODUCT_SK,
    dd.DATE_SK,
    sb.ORDER_ID,
    sb.ORDER_ITEM_ID,
    sb.PRODUCT_ID,
    sb.CUSTOMER_ID,
    sb.CUSTOMER_UNIQUE_ID,
    sb.ORDER_PURCHASE_TIMESTAMP,
    sb.ORDER_DATE,
    sb.PRICE,
    sb.FREIGHT_VALUE,
    sb.TOTAL_SALE_AMOUNT,
    CURRENT_TIMESTAMP() AS LOAD_TIMESTAMP
FROM sales_base sb
INNER JOIN DIM_CUSTOMER dc
    ON sb.CUSTOMER_UNIQUE_ID = dc.CUSTOMER_UNIQUE_ID
INNER JOIN DIM_PRODUCT dp
    ON sb.PRODUCT_ID = dp.PRODUCT_ID
INNER JOIN DIM_DATE dd
    ON sb.ORDER_DATE = dd.ORDER_DATE;