USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA GOLD;

CREATE OR REPLACE TABLE DIM_CUSTOMER AS
SELECT
    CUSTOMER_ID,
    CUSTOMER_UNIQUE_ID,
    CUSTOMER_CITY,
    CUSTOMER_STATE
FROM SILVER.SILVER_CUSTOMERS;

CREATE OR REPLACE TABLE DIM_PRODUCT AS
SELECT
    PRODUCT_ID,
    PRODUCT_CATEGORY_NAME,
    PRODUCT_WEIGHT_G
FROM SILVER.SILVER_PRODUCTS;

CREATE OR REPLACE TABLE DIM_DATE AS
SELECT DISTINCT
    CAST(ORDER_PURCHASE_TIMESTAMP AS DATE) AS ORDER_DATE,
    YEAR(ORDER_PURCHASE_TIMESTAMP) AS ORDER_YEAR,
    MONTH(ORDER_PURCHASE_TIMESTAMP) AS ORDER_MONTH,
    DAY(ORDER_PURCHASE_TIMESTAMP) AS ORDER_DAY,
    DAYOFWEEK(ORDER_PURCHASE_TIMESTAMP) AS DAY_OF_WEEK
FROM SILVER.SILVER_ORDERS
WHERE ORDER_PURCHASE_TIMESTAMP IS NOT NULL;

CREATE OR REPLACE TABLE FACT_SALES AS
SELECT
    oi.ORDER_ID,
    oi.ORDER_ITEM_ID,
    oi.PRODUCT_ID,
    o.CUSTOMER_ID,
    o.ORDER_PURCHASE_TIMESTAMP,
    CAST(o.ORDER_PURCHASE_TIMESTAMP AS DATE) AS ORDER_DATE,
    oi.PRICE,
    oi.FREIGHT_VALUE,
    oi.PRICE + oi.FREIGHT_VALUE AS TOTAL_SALE_AMOUNT
FROM SILVER.SILVER_ORDER_ITEMS oi
INNER JOIN SILVER.SILVER_ORDERS o
    ON oi.ORDER_ID = o.ORDER_ID;