USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA GOLD;

SELECT
    'DIM_CUSTOMER' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT
FROM DIM_CUSTOMER

UNION ALL

SELECT
    'DIM_PRODUCT' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT
FROM DIM_PRODUCT

UNION ALL

SELECT
    'DIM_DATE' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT
FROM DIM_DATE

UNION ALL

SELECT
    'FACT_SALES' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT
FROM FACT_SALES;