SELECT COUNT(*) AS CUSTOMER_DIM_COUNT
FROM DIM_CUSTOMERS;

SELECT COUNT(*) AS PRODUCT_DIM_COUNT
FROM DIM_PRODUCTS;

SELECT COUNT(*) AS FACT_SALES_COUNT
FROM FACT_SALES;

SELECT SUM(TOTAL_REVENUE) AS TOTAL_REVENUE
FROM FACT_SALES;