USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA GOLD;

SHOW TABLES IN SCHEMA GOLD;

SELECT 'DIM_CUSTOMER' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM DIM_CUSTOMER

UNION ALL

SELECT 'DIM_PRODUCT', COUNT(*)
FROM DIM_PRODUCT

UNION ALL

SELECT 'DIM_DATE', COUNT(*)
FROM DIM_DATE

UNION ALL

SELECT 'FACT_SALES', COUNT(*)
FROM FACT_SALES;