USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA GOLD;

SELECT
    CUSTOMER_ID,
    COUNT(*) AS TOTAL_PURCHASES,
    ROUND(SUM(PRICE + FREIGHT_VALUE), 2) AS TOTAL_SPEND,
    ROUND(AVG(PRICE + FREIGHT_VALUE), 2) AS AVG_ORDER_VALUE
FROM FACT_SALES
GROUP BY CUSTOMER_ID
ORDER BY TOTAL_SPEND DESC
LIMIT 25;