USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA GOLD;

SELECT
    CUSTOMER_ID,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM FACT_SALES
GROUP BY CUSTOMER_ID
HAVING COUNT(DISTINCT ORDER_ID) > 1
ORDER BY TOTAL_ORDERS DESC;