USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA GOLD;

WITH customer_orders AS (
    SELECT DISTINCT
        CUSTOMER_ID,
        ORDER_ID,
        ORDER_DATE
    FROM FACT_SALES
    WHERE CUSTOMER_ID IS NOT NULL
      AND ORDER_ID IS NOT NULL
      AND ORDER_DATE IS NOT NULL
),

customer_cohorts AS (
    SELECT
        CUSTOMER_ID,
        MIN(DATE_TRUNC('MONTH', ORDER_DATE)) AS FIRST_PURCHASE_MONTH
    FROM customer_orders
    GROUP BY CUSTOMER_ID
),

cohort_sizes AS (
    SELECT
        FIRST_PURCHASE_MONTH,
        COUNT(DISTINCT CUSTOMER_ID) AS COHORT_SIZE
    FROM customer_cohorts
    GROUP BY FIRST_PURCHASE_MONTH
),

customer_activity AS (
    SELECT
        co.CUSTOMER_ID,
        cc.FIRST_PURCHASE_MONTH,
        DATE_TRUNC('MONTH', co.ORDER_DATE) AS ACTIVITY_MONTH,
        DATEDIFF(
            'MONTH',
            cc.FIRST_PURCHASE_MONTH,
            DATE_TRUNC('MONTH', co.ORDER_DATE)
        ) AS MONTHS_SINCE_FIRST_PURCHASE
    FROM customer_orders co
    INNER JOIN customer_cohorts cc
        ON co.CUSTOMER_ID = cc.CUSTOMER_ID
)

SELECT
    ca.FIRST_PURCHASE_MONTH,
    ca.MONTHS_SINCE_FIRST_PURCHASE,
    cs.COHORT_SIZE,
    COUNT(DISTINCT ca.CUSTOMER_ID) AS RETAINED_CUSTOMERS,
    ROUND(
        COUNT(DISTINCT ca.CUSTOMER_ID) / NULLIF(cs.COHORT_SIZE, 0),
        4
    ) AS RETENTION_RATE
FROM customer_activity ca
INNER JOIN cohort_sizes cs
    ON ca.FIRST_PURCHASE_MONTH = cs.FIRST_PURCHASE_MONTH
GROUP BY
    ca.FIRST_PURCHASE_MONTH,
    ca.MONTHS_SINCE_FIRST_PURCHASE,
    cs.COHORT_SIZE
ORDER BY
    ca.FIRST_PURCHASE_MONTH,
    ca.MONTHS_SINCE_FIRST_PURCHASE;