USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA GOLD;

SELECT
    dc.CUSTOMER_ID,
    dc.CUSTOMER_CITY,
    dc.CUSTOMER_STATE,
    COUNT(DISTINCT fs.ORDER_ID) AS TOTAL_ORDERS,
    ROUND(SUM(fs.TOTAL_SALE_AMOUNT), 2) AS CUSTOMER_LIFETIME_VALUE
FROM FACT_SALES fs
LEFT JOIN DIM_CUSTOMER dc
    ON fs.CUSTOMER_SK = dc.CUSTOMER_SK
GROUP BY
    dc.CUSTOMER_ID,
    dc.CUSTOMER_CITY,
    dc.CUSTOMER_STATE
ORDER BY CUSTOMER_LIFETIME_VALUE DESC
LIMIT 25;