USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA GOLD;

SELECT
    CUSTOMER_ID,
    ROUND(SUM(TOTAL_SALE_AMOUNT),2) AS CUSTOMER_LIFETIME_VALUE
FROM FACT_SALES
GROUP BY CUSTOMER_ID
ORDER BY CUSTOMER_LIFETIME_VALUE DESC
LIMIT 25;