USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA GOLD;

SELECT
    DATE_TRUNC('MONTH', ORDER_DATE) AS SALES_MONTH,
    ROUND(SUM(TOTAL_SALE_AMOUNT), 2) AS MONTHLY_REVENUE
FROM FACT_SALES
GROUP BY SALES_MONTH
ORDER BY SALES_MONTH;