USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA GOLD;

SELECT
    dc.CUSTOMER_STATE,
    ROUND(SUM(fs.TOTAL_SALE_AMOUNT),2) AS REVENUE
FROM FACT_SALES fs
JOIN DIM_CUSTOMER dc
ON fs.CUSTOMER_ID = dc.CUSTOMER_ID
GROUP BY dc.CUSTOMER_STATE
ORDER BY REVENUE DESC;