USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA GOLD;

SELECT
    dc.CUSTOMER_STATE,
    COUNT(DISTINCT fs.ORDER_ID) AS TOTAL_ORDERS,
    COUNT(DISTINCT fs.CUSTOMER_UNIQUE_ID) AS TOTAL_CUSTOMERS,
    ROUND(SUM(fs.TOTAL_SALE_AMOUNT), 2) AS REVENUE
FROM FACT_SALES fs
INNER JOIN DIM_CUSTOMER dc
    ON fs.CUSTOMER_SK = dc.CUSTOMER_SK
WHERE dc.CUSTOMER_STATE IS NOT NULL
GROUP BY dc.CUSTOMER_STATE
ORDER BY REVENUE DESC;