USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA GOLD;

SELECT
    dp.PRODUCT_ID,
    dp.PRODUCT_CATEGORY_NAME,
    ROUND(SUM(fs.TOTAL_SALE_AMOUNT), 2) AS REVENUE
FROM FACT_SALES fs
LEFT JOIN DIM_PRODUCT dp
    ON fs.PRODUCT_SK = dp.PRODUCT_SK
GROUP BY
    dp.PRODUCT_ID,
    dp.PRODUCT_CATEGORY_NAME
ORDER BY REVENUE DESC
LIMIT 10;