USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA GOLD;

SELECT
    dp.PRODUCT_ID,
    dp.PRODUCT_CATEGORY_NAME,
    COUNT(DISTINCT fs.ORDER_ID) AS TOTAL_ORDERS,
    COUNT(*) AS TOTAL_ORDER_ITEMS,
    ROUND(SUM(fs.TOTAL_SALE_AMOUNT), 2) AS REVENUE
FROM FACT_SALES fs
INNER JOIN DIM_PRODUCT dp
    ON fs.PRODUCT_SK = dp.PRODUCT_SK
WHERE dp.PRODUCT_ID IS NOT NULL
GROUP BY
    dp.PRODUCT_ID,
    dp.PRODUCT_CATEGORY_NAME
ORDER BY REVENUE DESC
LIMIT 10;