USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA GOLD;

SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT ORDER_ID) AS DISTINCT_ORDERS,
    COUNT(DISTINCT CUSTOMER_ID) AS DISTINCT_CUSTOMERS,
    COUNT(DISTINCT PRODUCT_ID) AS DISTINCT_PRODUCTS,
    ROUND(SUM(TOTAL_SALE_AMOUNT), 2) AS TOTAL_REVENUE,
    MIN(ORDER_DATE) AS FIRST_ORDER_DATE,
    MAX(ORDER_DATE) AS LAST_ORDER_DATE
FROM FACT_SALES;