USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA GOLD;

SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT ORDER_ID) AS DISTINCT_ORDERS,
    COUNT(DISTINCT CUSTOMER_ID) AS DISTINCT_CUSTOMERS,
    COUNT(DISTINCT PRODUCT_ID) AS DISTINCT_PRODUCTS,
    ROUND(SUM(PRICE + FREIGHT_VALUE), 2) AS TOTAL_REVENUE
FROM FACT_SALES;