USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA GOLD;

SELECT
    COUNT(*) AS FACT_SALES_ROWS,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    COUNT(DISTINCT CUSTOMER_UNIQUE_ID) AS TOTAL_CUSTOMERS,
    COUNT(DISTINCT PRODUCT_ID) AS TOTAL_PRODUCTS,
    ROUND(SUM(TOTAL_SALE_AMOUNT), 2) AS TOTAL_REVENUE,
    MIN(ORDER_DATE) AS FIRST_ORDER_DATE,
    MAX(ORDER_DATE) AS LAST_ORDER_DATE
FROM FACT_SALES;