USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA BRONZE;

CREATE OR REPLACE TABLE BRONZE_CUSTOMERS
(
    CUSTOMER_ID STRING,
    CUSTOMER_UNIQUE_ID STRING,
    CUSTOMER_ZIP_CODE_PREFIX NUMBER,
    CUSTOMER_CITY STRING,
    CUSTOMER_STATE STRING,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE BRONZE_ORDERS
(
    ORDER_ID STRING,
    CUSTOMER_ID STRING,
    ORDER_STATUS STRING,
    ORDER_PURCHASE_TIMESTAMP TIMESTAMP,
    ORDER_APPROVED_AT TIMESTAMP,
    ORDER_DELIVERED_CARRIER_DATE TIMESTAMP,
    ORDER_DELIVERED_CUSTOMER_DATE TIMESTAMP,
    ORDER_ESTIMATED_DELIVERY_DATE TIMESTAMP,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE BRONZE_PRODUCTS
(
    PRODUCT_ID STRING,
    PRODUCT_CATEGORY_NAME STRING,
    PRODUCT_NAME_LENGTH NUMBER,
    PRODUCT_DESCRIPTION_LENGTH NUMBER,
    PRODUCT_PHOTOS_QTY NUMBER,
    PRODUCT_WEIGHT_G NUMBER,
    PRODUCT_LENGTH_CM NUMBER,
    PRODUCT_HEIGHT_CM NUMBER,
    PRODUCT_WIDTH_CM NUMBER,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE BRONZE_ORDER_ITEMS
(
    ORDER_ID STRING,
    ORDER_ITEM_ID NUMBER,
    PRODUCT_ID STRING,
    SELLER_ID STRING,
    SHIPPING_LIMIT_DATE TIMESTAMP,
    PRICE NUMBER(10,2),
    FREIGHT_VALUE NUMBER(10,2),
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);