USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA BRONZE;

COPY INTO BRONZE_CUSTOMERS
FROM @RETAIL_STAGE/olist_customers_dataset.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO BRONZE_ORDERS
FROM @RETAIL_STAGE/olist_orders_dataset.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO BRONZE_PRODUCTS
FROM @RETAIL_STAGE/olist_products_dataset.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO BRONZE_ORDER_ITEMS
FROM @RETAIL_STAGE/olist_order_items_dataset.csv
FILE_FORMAT = CSV_FORMAT;