USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA BRONZE;

COPY INTO BRONZE_CUSTOMERS
(
    CUSTOMER_ID,
    CUSTOMER_UNIQUE_ID,
    CUSTOMER_ZIP_CODE_PREFIX,
    CUSTOMER_CITY,
    CUSTOMER_STATE
)
FROM @RETAIL_STAGE/olist_customers_dataset.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO BRONZE_ORDERS
(
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_STATUS,
    ORDER_PURCHASE_TIMESTAMP,
    ORDER_APPROVED_AT,
    ORDER_DELIVERED_CARRIER_DATE,
    ORDER_DELIVERED_CUSTOMER_DATE,
    ORDER_ESTIMATED_DELIVERY_DATE
)
FROM @RETAIL_STAGE/olist_orders_dataset.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO BRONZE_PRODUCTS
(
    PRODUCT_ID,
    PRODUCT_CATEGORY_NAME,
    PRODUCT_NAME_LENGTH,
    PRODUCT_DESCRIPTION_LENGTH,
    PRODUCT_PHOTOS_QTY,
    PRODUCT_WEIGHT_G,
    PRODUCT_LENGTH_CM,
    PRODUCT_HEIGHT_CM,
    PRODUCT_WIDTH_CM
)
FROM @RETAIL_STAGE/olist_products_dataset.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO BRONZE_ORDER_ITEMS
(
    ORDER_ID,
    ORDER_ITEM_ID,
    PRODUCT_ID,
    SELLER_ID,
    SHIPPING_LIMIT_DATE,
    PRICE,
    FREIGHT_VALUE
)
FROM @RETAIL_STAGE/olist_order_items_dataset.csv
FILE_FORMAT = CSV_FORMAT;