SELECT COUNT(*) AS CUSTOMER_COUNT
FROM BRONZE_CUSTOMERS;

SELECT COUNT(*) AS ORDER_COUNT
FROM BRONZE_ORDERS;

SELECT COUNT(*) AS PRODUCT_COUNT
FROM BRONZE_PRODUCTS;

SELECT COUNT(*) AS ORDER_ITEM_COUNT
FROM BRONZE_ORDER_ITEMS;

SELECT *
FROM BRONZE_CUSTOMERS
LIMIT 10;

SELECT *
FROM BRONZE_ORDERS
LIMIT 10;

SELECT *
FROM BRONZE_PRODUCTS
LIMIT 10;

SELECT *
FROM BRONZE_ORDER_ITEMS
LIMIT 10;