USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA BRONZE;

SELECT 'BRONZE_CUSTOMERS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM BRONZE_CUSTOMERS

UNION ALL

SELECT 'BRONZE_ORDERS', COUNT(*)
FROM BRONZE_ORDERS

UNION ALL

SELECT 'BRONZE_PRODUCTS', COUNT(*)
FROM BRONZE_PRODUCTS

UNION ALL

SELECT 'BRONZE_ORDER_ITEMS', COUNT(*)
FROM BRONZE_ORDER_ITEMS;