USE DATABASE RETAIL_ANALYTICS_DB;
CREATE SCHEMA IF NOT EXISTS BRONZE;
USE SCHEMA BRONZE;

CREATE OR REPLACE TABLE BRONZE_PIPELINE_TEST (
    TEST_ID NUMBER,
    TEST_NAME STRING,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO BRONZE_PIPELINE_TEST (TEST_ID, TEST_NAME)
VALUES (1, 'bronze ci/cd test');
