USE DATABASE RETAIL_ANALYTICS_DB;
CREATE SCHEMA IF NOT EXISTS GOLD;
USE SCHEMA GOLD;

CREATE OR REPLACE TABLE GOLD_PIPELINE_TEST AS
SELECT COUNT(*) AS TOTAL_ROWS
FROM RETAIL_ANALYTICS_DB.SILVER.SILVER_PIPELINE_TEST;
