USE DATABASE RETAIL_ANALYTICS_DB;
CREATE SCHEMA IF NOT EXISTS SILVER;
USE SCHEMA SILVER;

CREATE OR REPLACE TABLE SILVER_PIPELINE_TEST AS
SELECT *
FROM RETAIL_ANALYTICS_DB.BRONZE.BRONZE_PIPELINE_TEST;
