name: Data Pipeline CI

on:
  push:
    branches:
      - main

jobs:
  run-pipeline:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Packages
      run: |
        pip install pandas

    - name: Run Pipeline
      run: |
        python orchestration/pipeline.py