name: Retail Analytics Pipeline

on:
  push:
    branches: [ main ]

jobs:
  run-etl-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install SnowSQL
        run: |
          curl -L -o snowsql.bash https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.32-linux_x86_64.bash
          ls -lah
          bash snowsql.bash -y
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Verify SnowSQL
        run: |
          snowsql -v

      - name: Run Snowflake SQL scripts
        env:
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWSQL_PWD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWSQL_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWSQL_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWSQL_DATABASE: RETAIL_ANALYTICS_DB
          SNOWSQL_SCHEMA: PUBLIC
        run: |
          snowsql -f sql/bronze.sql
          snowsql -f sql/silver.sql
          snowsql -f sql/gold.sql
